import requests
from bs4 import BeautifulSoup
import time
import os
import logging
from concurrent.futures import ThreadPoolExecutor, as_completed

# 配置日志
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# 监控的网页列表及其对应的保存文件名
urls = {
    "https://www.vmiba.com/13509.html": None,
    "https://www.vmiba.com/13505.html": None,
    "https://www.vmiba.com/13499.html": None,
    "https://www.vmiba.com/13496.html": None,
    "https://www.vmiba.com/13487.html": None,
    "https://www.vmiba.com/13113.html": None,
    "https://www.vmiba.com/13109.html": None,
    "https://www.vmiba.com/13104.html": None,
    "https://www.vmiba.com/13100.html": None,
    "https://www.vmiba.com/13091.html": None,
    "https://www.vmiba.com/12792.html": None,
    "https://www.vmiba.com/12788.html": None,
    "https://www.vmiba.com/12785.html": None,
    "https://www.vmiba.com/12781.html": None,
    "https://www.vmiba.com/12771.html": None,
    "https://www.vmiba.com/12366.html": None,
    "https://www.vmiba.com/12362.html": None,
    "https://www.vmiba.com/12358.html": None,
    "https://www.vmiba.com/12350.html": None,
    "https://www.vmiba.com/12343.html": None,
    "https://www.vmiba.com/12064.html": None,
    "https://www.vmiba.com/12060.html": None,
    "https://www.vmiba.com/12056.html": None,
    "https://www.vmiba.com/12051.html": None,
    "https://www.vmiba.com/12042.html": None,
    "https://www.vmiba.com/11683.html": None,
    "https://www.vmiba.com/11679.html": None,
    "https://www.vmiba.com/11674.html": None,
    "https://www.vmiba.com/11670.html": None,
    "https://www.vmiba.com/11662.html": None,
    "https://www.vmiba.com/11024.html": None,
    "https://www.vmiba.com/11052.html": None,
    "https://www.vmiba.com/11048.html": None,
    "https://www.vmiba.com/11043.html": None,
    "https://www.vmiba.com/11039.html": None,
    "https://www.vmiba.com/10932.html": None,
    "https://www.vmiba.com/10928.html": None,
    "https://www.vmiba.com/10925.html": None,
    "https://www.vmiba.com/10919.html": None,
    "https://www.vmiba.com/10912.html": None,
    "https://www.vmiba.com/10532.html": None,
    "https://www.vmiba.com/10526.html": None,
    "https://www.vmiba.com/10522.html": None,
    "https://www.vmiba.com/10515.html": None,
    "https://www.vmiba.com/10507.html": None,
    "https://www.vmiba.com/10329.html": None,
    "https://www.vmiba.com/10322.html": None,
    "https://www.vmiba.com/10317.html": None,
    "https://www.vmiba.com/10310.html": None,
    "https://www.vmiba.com/10302.html": None,
    "https://www.vmiba.com/9805.html ": None,
    "https://www.vmiba.com/9800.html ": None,
    "https://www.vmiba.com/9795.html ": None,
    "https://www.vmiba.com/9641.html ": None,
    "https://www.vmiba.com/9634.html ": None,
    "https://www.vmiba.com/9629.html ": None,
    "https://www.vmiba.com/9324.html ": None,
    "https://www.vmiba.com/9321.html ": None,
    "https://www.vmiba.com/9312.html ": None,
    "https://www.vmiba.com/9263.html ": None,
    "https://www.vmiba.com/13773.html": None,
    "https://www.vmiba.com/13734.html": None,
    "https://www.vmiba.com/13708.html": None,
    "https://www.vmiba.com/13722.html": None,
    "https://www.vmiba.com/13706.html": None,
    "https://www.vmiba.com/13699.html": None,
    "https://www.vmiba.com/2364.html ": None,
    "https://www.vmiba.com/13646.html": None,
    "https://www.vmiba.com/795.html  ": None,
    "https://www.vmiba.com/6304.html ": None,
    "https://www.vmiba.com/13703.html": None,
    "https://www.vmiba.com/13694.html": None,
    "https://www.vmiba.com/13687.html": None,
    "https://www.vmiba.com/13674.html": None,
    "https://www.vmiba.com/13668.html": None,
    "https://www.vmiba.com/13656.html": None,
    "https://www.vmiba.com/2146.html ": None,
    "https://www.vmiba.com/13641.html": None,
    "https://www.vmiba.com/13636.html": None,
    "https://www.vmiba.com/11234.html": None,
    "https://www.vmiba.com/12088.html": None,
    "https://www.vmiba.com/11356.html": None,
    "https://www.vmiba.com/13358.html": None,
    "https://www.vmiba.com/12821.html": None,
    "https://www.vmiba.com/11841.html": None,
    "https://www.vmiba.com/410.html  ": None,
    "https://www.vmiba.com/11734.html": None,
    "https://www.vmiba.com/11324.html": None,
    "https://www.vmiba.com/12877.html": None,
    "https://www.vmiba.com/1598.html ": None,
    "https://www.vmiba.com/11420.html": None,
    "https://www.vmiba.com/12175.html": None,
    "https://www.vmiba.com/13417.html": None,
    "https://www.vmiba.com/13594.html": None,
    "https://www.vmiba.com/13592.html": None,
    "https://www.vmiba.com/13590.html": None,
    "https://www.vmiba.com/13584.html": None,
    "https://www.vmiba.com/7912.html ": None,
    "https://www.vmiba.com/12884.html": None,
    "https://www.vmiba.com/518.html  ": None,
    "https://www.vmiba.com/7744.html ": None,
    "https://www.vmiba.com/12832.html": None,
    "https://www.vmiba.com/12829.html": None,
    "https://www.vmiba.com/6599.html ": None,
    "https://www.vmiba.com/8391.html ": None,
    "https://www.vmiba.com/1587.html ": None,
    "https://www.vmiba.com/787.html  ": None,
    "https://www.vmiba.com/12738.html": None,
    "https://www.vmiba.com/13533.html": None,
    "https://www.vmiba.com/13524.html": None,
    "https://www.vmiba.com/9394.html ": None,
    "https://www.vmiba.com/12880.html": None,
    "https://www.vmiba.com/13345.html": None,
    "https://www.vmiba.com/2980.html ": None,
    "https://www.vmiba.com/13464.html": None,
    "https://www.vmiba.com/779.html  ": None,
    "https://www.vmiba.com/3593.html ": None,
    "https://www.vmiba.com/4741.html ": None,
    "https://www.vmiba.com/4232.html ": None,
    "https://www.vmiba.com/3895.html ": None,
    "https://www.vmiba.com/5817.html ": None,
    "https://www.vmiba.com/13446.html": None,
    "https://www.vmiba.com/11203.html": None,
    "https://www.vmiba.com/11898.html": None,
    "https://www.vmiba.com/11413.html": None,
    "https://www.vmiba.com/11270.html": None,
    "https://www.vmiba.com/11365.html": None,
    "https://www.vmiba.com/8006.html ": None,
    "https://www.vmiba.com/13413.html": None,
    "https://www.vmiba.com/3378.html ": None,
    "https://www.vmiba.com/12612.html": None,
    "https://www.vmiba.com/12694.html": None,
    "https://www.vmiba.com/2372.html ": None,
    "https://www.vmiba.com/789.html  ": None,
    "https://www.vmiba.com/13380.html": None,
    "https://www.vmiba.com/13375.html": None,
    "https://www.vmiba.com/13364.html": None,
    "https://www.vmiba.com/11277.html": None,
    "https://www.vmiba.com/13326.html": None,
    "https://www.vmiba.com/13317.html": None,
    "https://www.vmiba.com/13332.html": None,
    "https://www.vmiba.com/13288.html": None,
    "https://www.vmiba.com/13283.html": None,
    "https://www.vmiba.com/13298.html": None,
    "https://www.vmiba.com/2639.html ": None,
    "https://www.vmiba.com/6667.html ": None,
    "https://www.vmiba.com/10692.html": None,
    "https://www.vmiba.com/13260.html": None,
    "https://www.vmiba.com/11869.html": None,
    "https://www.vmiba.com/13258.html": None,
    "https://www.vmiba.com/3436.html ": None,
    "https://www.vmiba.com/13248.html": None,
    "https://www.vmiba.com/13244.html": None,
    "https://www.vmiba.com/13235.html": None,
    "https://www.vmiba.com/13223.html": None,
    "https://www.vmiba.com/13217.html": None,
    "https://www.vmiba.com/13210.html": None,
    "https://www.vmiba.com/13199.html": None,
    "https://www.vmiba.com/9516.html ": None,
    "https://www.vmiba.com/13167.html": None,
    "https://www.vmiba.com/11863.html": None,
    "https://www.vmiba.com/6119.html ": None,
    "https://www.vmiba.com/12193.html": None,
    "https://www.vmiba.com/5336.html ": None,
    "https://www.vmiba.com/7261.html ": None,
    "https://www.vmiba.com/720.html  ": None,
    "https://www.vmiba.com/6083.html ": None,
    "https://www.vmiba.com/287.html  ": None,
    "https://www.vmiba.com/10823.html": None,
    "https://www.vmiba.com/2132.html ": None,
    "https://www.vmiba.com/980.html  ": None,
    "https://www.vmiba.com/13042.html": None,
    "https://www.vmiba.com/3383.html ": None,
    "https://www.vmiba.com/1981.html ": None,
    "https://www.vmiba.com/12034.html": None,
    "https://www.vmiba.com/11247.html": None,
    "https://www.vmiba.com/13029.html": None,
    "https://www.vmiba.com/7269.html ": None,
    "https://www.vmiba.com/12985.html": None,
    "https://www.vmiba.com/11810.html": None,
    "https://www.vmiba.com/976.html  ": None,
    "https://www.vmiba.com/651.html  ": None,
    "https://www.vmiba.com/11443.html": None,
    "https://www.vmiba.com/12882.html": None,
    "https://www.vmiba.com/12870.html": None,
    "https://www.vmiba.com/12827.html": None,
    "https://www.vmiba.com/649.html  ": None,
    "https://www.vmiba.com/1579.html ": None,
    "https://www.vmiba.com/12764.html": None,
    "https://www.vmiba.com/12760.html": None,
    "https://www.vmiba.com/12729.html": None,
    "https://www.vmiba.com/12715.html": None,
    "https://www.vmiba.com/12398.html": None,
    "https://www.vmiba.com/1771.html ": None,
    "https://www.vmiba.com/12701.html": None,
    "https://www.vmiba.com/12699.html": None,
    "https://www.vmiba.com/12665.html": None,
    "https://www.vmiba.com/2013.html ": None,
    "https://www.vmiba.com/9181.html ": None,
    "https://www.vmiba.com/277.html  ": None,
    "https://www.vmiba.com/11894.html": None,
    "https://www.vmiba.com/3093.html ": None,
    "https://www.vmiba.com/2689.html ": None,
    "https://www.vmiba.com/12634.html": None,
    "https://www.vmiba.com/12491.html": None,
    "https://www.vmiba.com/3292.html ": None,
    "https://www.vmiba.com/427.html  ": None,
    "https://www.vmiba.com/12616.html": None,
    "https://www.vmiba.com/4510.html ": None,
    "https://www.vmiba.com/12594.html": None,
    "https://www.vmiba.com/4137.html ": None,
    "https://www.vmiba.com/12523.html": None,
    "https://www.vmiba.com/12579.html": None,
    "https://www.vmiba.com/669.html  ": None,
    "https://www.vmiba.com/5431.html ": None,
    "https://www.vmiba.com/6524.html ": None,
    "https://www.vmiba.com/11753.html": None,
    "https://www.vmiba.com/6690.html ": None,
    "https://www.vmiba.com/12489.html": None,
    "https://www.vmiba.com/12487.html": None,
    "https://www.vmiba.com/12485.html": None,
    "https://www.vmiba.com/2920.html ": None,
    "https://www.vmiba.com/1068.html ": None,
    "https://www.vmiba.com/6893.html ": None,
    "https://www.vmiba.com/12402.html": None,
    "https://www.vmiba.com/12394.html": None,
    "https://www.vmiba.com/1583.html ": None,
    "https://www.vmiba.com/972.html  ": None,
    "https://www.vmiba.com/974.html  ": None,
    "https://www.vmiba.com/12321.html": None,
    "https://www.vmiba.com/11326.html": None,
    "https://www.vmiba.com/11152.html": None,
    "https://www.vmiba.com/12301.html": None,
    "https://www.vmiba.com/12297.html": None,
    "https://www.vmiba.com/4393.html ": None,
    "https://www.vmiba.com/1985.html ": None,
    "https://www.vmiba.com/667.html  ": None,
    "https://www.vmiba.com/12187.html": None,
    "https://www.vmiba.com/1782.html ": None,
    "https://www.vmiba.com/10868.html": None,
    "https://www.vmiba.com/1057.html ": None,
    "https://www.vmiba.com/6660.html ": None,
    "https://www.vmiba.com/7993.html ": None,
    "https://www.vmiba.com/11425.html": None,
    "https://www.vmiba.com/12195.html": None,
    "https://www.vmiba.com/2635.html ": None,
    "https://www.vmiba.com/12148.html": None,
    "https://www.vmiba.com/1119.html ": None,
    "https://www.vmiba.com/2632.html ": None,
    "https://www.vmiba.com/11855.html": None,
    "https://www.vmiba.com/6622.html ": None,
    "https://www.vmiba.com/11318.html": None,
    "https://www.vmiba.com/3233.html ": None,
    "https://www.vmiba.com/4876.html ": None,
    "https://www.vmiba.com/6957.html ": None,
    "https://www.vmiba.com/7187.html ": None,
    "https://www.vmiba.com/9914.html ": None,
    "https://www.vmiba.com/12030.html": None,
    "https://www.vmiba.com/1059.html ": None,
    "https://www.vmiba.com/11981.html": None,
    "https://www.vmiba.com/11974.html": None,
    "https://www.vmiba.com/11967.html": None,
    "https://www.vmiba.com/11963.html": None,
    "https://www.vmiba.com/419.html  ": None,
    "https://www.vmiba.com/5582.html ": None,
    "https://www.vmiba.com/11881.html": None,
    "https://www.vmiba.com/1602.html ": None,
    "https://www.vmiba.com/781.html  ": None,
    "https://www.vmiba.com/11850.html": None,
    "https://www.vmiba.com/11283.html": None,
    "https://www.vmiba.com/8583.html ": None,
    "https://www.vmiba.com/8917.html ": None,
    "https://www.vmiba.com/5090.html ": None,
    "https://www.vmiba.com/8512.html ": None,
    "https://www.vmiba.com/7998.html ": None,
    "https://www.vmiba.com/4696.html ": None,
    "https://www.vmiba.com/5992.html ": None,
    "https://www.vmiba.com/2685.html ": None,
    "https://www.vmiba.com/3666.html ": None,
    "https://www.vmiba.com/2872.html ": None,
    "https://www.vmiba.com/5270.html ": None,
    "https://www.vmiba.com/3658.html ": None,
    "https://www.vmiba.com/2447.html ": None,
    "https://www.vmiba.com/5409.html ": None,
    "https://www.vmiba.com/5007.html ": None,
    "https://www.vmiba.com/5011.html ": None,
    "https://www.vmiba.com/3517.html ": None,
    "https://www.vmiba.com/2627.html ": None,
    "https://www.vmiba.com/11543.html": None,
    "https://www.vmiba.com/11721.html": None,
    "https://www.vmiba.com/11718.html": None,
    "https://www.vmiba.com/11712.html": None,
    "https://www.vmiba.com/3142.html ": None,
    "https://www.vmiba.com/2670.html ": None,
    "https://www.vmiba.com/1085.html ": None,
    "https://www.vmiba.com/1100.html ": None,
    "https://www.vmiba.com/1250.html ": None,
    "https://www.vmiba.com/11363.html": None,
    "https://www.vmiba.com/11243.html": None,
    "https://www.vmiba.com/1111.html ": None,
    "https://www.vmiba.com/2063.html ": None,
    "https://www.vmiba.com/1284.html ": None,
    "https://www.vmiba.com/11636.html": None,
    "https://www.vmiba.com/11633.html": None,
    "https://www.vmiba.com/5023.html ": None,
    "https://www.vmiba.com/3898.html ": None,
    "https://www.vmiba.com/7491.html ": None,
    "https://www.vmiba.com/5402.html ": None,
    "https://www.vmiba.com/7225.html ": None,
    "https://www.vmiba.com/339.html  ": None,
    "https://www.vmiba.com/990.html  ": None,
    "https://www.vmiba.com/11367.html": None,
    "https://www.vmiba.com/11559.html": None,
    "https://www.vmiba.com/11553.html": None,
    "https://www.vmiba.com/11520.html": None,
    "https://www.vmiba.com/11513.html": None,
    "https://www.vmiba.com/11483.html": None,
    "https://www.vmiba.com/11489.html": None,
    "https://www.vmiba.com/11463.html": None,
    "https://www.vmiba.com/5194.html ": None,
    "https://www.vmiba.com/986.html  ": None,
    "https://www.vmiba.com/6407.html ": None,
    "https://www.vmiba.com/11427.html": None,
    "https://www.vmiba.com/11423.html": None,
    "https://www.vmiba.com/1232.html ": None,
    "https://www.vmiba.com/11139.html": None,
    "https://www.vmiba.com/11369.html": None,
    "https://www.vmiba.com/11321.html": None,
    "https://www.vmiba.com/11310.html": None,
    "https://www.vmiba.com/11281.html": None,
    "https://www.vmiba.com/11279.html": None,
    "https://www.vmiba.com/11245.html": None,
    "https://www.vmiba.com/11241.html": None,
    "https://www.vmiba.com/11207.html": None,
    "https://www.vmiba.com/11205.html": None,
    "https://www.vmiba.com/11201.html": None,
    "https://www.vmiba.com/11194.html": None,
    "https://www.vmiba.com/11150.html": None,
    "https://www.vmiba.com/11148.html": None,
    "https://www.vmiba.com/11146.html": None,
    "https://www.vmiba.com/4425.html ": None,
    "https://www.vmiba.com/7214.html ": None,
    "https://www.vmiba.com/510.html  ": None,
    "https://www.vmiba.com/2353.html ": None,
    "https://www.vmiba.com/978.html  ": None,
    "https://www.vmiba.com/5971.html ": None,
    "https://www.vmiba.com/9010.html ": None,
    "https://www.vmiba.com/2152.html ": None,
    "https://www.vmiba.com/10965.html": None,
    "https://www.vmiba.com/1767.html ": None,
    "https://www.vmiba.com/1067.html ": None,
    "https://www.vmiba.com/1773.html ": None,
    "https://www.vmiba.com/2355.html ": None,
    "https://www.vmiba.com/505.html  ": None,
    "https://www.vmiba.com/6791.html ": None,
    "https://www.vmiba.com/2936.html ": None,
    "https://www.vmiba.com/6984.html ": None,
    "https://www.vmiba.com/2943.html ": None,
    "https://www.vmiba.com/1130.html ": None,
    "https://www.vmiba.com/503.html  ": None,
    "https://www.vmiba.com/6023.html ": None,
    "https://www.vmiba.com/2366.html ": None,
    "https://www.vmiba.com/5067.html ": None,
    "https://www.vmiba.com/2150.html ": None,
    "https://www.vmiba.com/777.html  ": None,
    "https://www.vmiba.com/5588.html ": None,
    "https://www.vmiba.com/4572.html ": None,
    "https://www.vmiba.com/508.html  ": None,
    "https://www.vmiba.com/7299.html ": None,
    "https://www.vmiba.com/283.html  ": None,
    "https://www.vmiba.com/2360.html ": None,
    "https://www.vmiba.com/10636.html": None,
    "https://www.vmiba.com/655.html  ": None,
    "https://www.vmiba.com/412.html  ": None,
    "https://www.vmiba.com/2631.html ": None,
    "https://www.vmiba.com/5978.html ": None,
    "https://www.vmiba.com/10475.html": None,
    "https://www.vmiba.com/1589.html ": None,
    "https://www.vmiba.com/417.html  ": None,
    "https://www.vmiba.com/1050.html ": None,
    "https://www.vmiba.com/3932.html ": None,
    "https://www.vmiba.com/1625.html ": None,
    "https://www.vmiba.com/2637.html ": None,
    "https://www.vmiba.com/7388.html ": None,
    "https://www.vmiba.com/10147.html": None,
    "https://www.vmiba.com/9982.html ": None,
    "https://www.vmiba.com/9978.html ": None,
    "https://www.vmiba.com/9502.html ": None,
    "https://www.vmiba.com/7865.html ": None,
    "https://www.vmiba.com/3231.html ": None,
    "https://www.vmiba.com/3103.html ": None,
    "https://www.vmiba.com/9851.html ": None,
    "https://www.vmiba.com/9832.html ": None,
    "https://www.vmiba.com/9781.html ": None,
    "https://www.vmiba.com/9774.html ": None,
    "https://www.vmiba.com/9779.html ": None,
    "https://www.vmiba.com/4268.html ": None,
    "https://www.vmiba.com/9734.html ": None,
    "https://www.vmiba.com/9720.html ": None,
    "https://www.vmiba.com/9714.html ": None,
    "https://www.vmiba.com/9694.html ": None,
    "https://www.vmiba.com/9691.html ": None,
    "https://www.vmiba.com/9685.html ": None,
    "https://www.vmiba.com/7762.html ": None,
    "https://www.vmiba.com/3672.html ": None,
    "https://www.vmiba.com/9527.html ": None,
    "https://www.vmiba.com/9511.html ": None,
    "https://www.vmiba.com/9509.html ": None,
    "https://www.vmiba.com/9472.html ": None,
    "https://www.vmiba.com/2158.html ": None,
    "https://www.vmiba.com/9457.html ": None,
    "https://www.vmiba.com/7208.html ": None,
    "https://www.vmiba.com/4492.html ": None,
    "https://www.vmiba.com/3096.html ": None,
    "https://www.vmiba.com/1064.html ": None,
    "https://www.vmiba.com/9350.html ": None,
    "https://www.vmiba.com/9344.html ": None,
    "https://www.vmiba.com/8552.html ": None,
    "https://www.vmiba.com/2938.html ": None,
    "https://www.vmiba.com/423.html  ": None,
    "https://www.vmiba.com/9178.html ": None,
    "https://www.vmiba.com/425.html  ": None,
    "https://www.vmiba.com/6471.html ": None,
    "https://www.vmiba.com/9054.html ": None,
    "https://www.vmiba.com/2934.html ": None,
    "https://www.vmiba.com/7078.html ": None,
    "https://www.vmiba.com/7035.html ": None,
    "https://www.vmiba.com/6288.html ": None,
    "https://www.vmiba.com/4143.html ": None,
    "https://www.vmiba.com/1581.html ": None,
    "https://www.vmiba.com/8936.html ": None,
    "https://www.vmiba.com/8927.html ": None,
    "https://www.vmiba.com/1780.html ": None,
    "https://www.vmiba.com/6224.html ": None,
    "https://www.vmiba.com/2641.html ": None,
    "https://www.vmiba.com/7355.html ": None,
    "https://www.vmiba.com/3704.html ": None,
    "https://www.vmiba.com/5261.html ": None,
    "https://www.vmiba.com/6922.html ": None,
    "https://www.vmiba.com/421.html  ": None,
    "https://www.vmiba.com/2441.html ": None,
    "https://www.vmiba.com/8696.html ": None,
    "https://www.vmiba.com/8693.html ": None,
    "https://www.vmiba.com/6987.html ": None,
    "https://www.vmiba.com/8666.html ": None,
    "https://www.vmiba.com/8628.html ": None,
    "https://www.vmiba.com/8615.html ": None,
    "https://www.vmiba.com/3432.html ": None,
    "https://www.vmiba.com/7176.html ": None,
    "https://www.vmiba.com/1240.html ": None,
    "https://www.vmiba.com/7221.html ": None,
    "https://www.vmiba.com/1234.html ": None,
    "https://www.vmiba.com/514.html  ": None,
    "https://www.vmiba.com/8357.html ": None,
    "https://www.vmiba.com/8377.html ": None,
    "https://www.vmiba.com/8316.html ": None,
    "https://www.vmiba.com/7027.html ": None,
    "https://www.vmiba.com/3104.html ": None,
    "https://www.vmiba.com/4284.html ": None,
    "https://www.vmiba.com/6655.html ": None,
    "https://www.vmiba.com/3784.html ": None,
    "https://www.vmiba.com/4884.html ": None,
    "https://www.vmiba.com/8208.html ": None,
    "https://www.vmiba.com/4414.html ": None,
    "https://www.vmiba.com/1053.html ": None,
    "https://www.vmiba.com/1769.html ": None,
    "https://www.vmiba.com/520.html  ": None,
    "https://www.vmiba.com/1700.html ": None,
    "https://www.vmiba.com/8081.html ": None,
    "https://www.vmiba.com/653.html  ": None,
    "https://www.vmiba.com/4674.html ": None,
    "https://www.vmiba.com/7338.html ": None,
    "https://www.vmiba.com/4763.html ": None,
    "https://www.vmiba.com/7399.html ": None,
    "https://www.vmiba.com/7878.html ": None,
    "https://www.vmiba.com/7812.html ": None,
    "https://www.vmiba.com/7008.html ": None,
    "https://www.vmiba.com/7713.html ": None,
    "https://www.vmiba.com/7708.html ": None,
    "https://www.vmiba.com/1785.html ": None,
    "https://www.vmiba.com/7116.html ": None,
    "https://www.vmiba.com/7650.html ": None,
    "https://www.vmiba.com/6368.html ": None,
    "https://www.vmiba.com/7622.html ": None,
    "https://www.vmiba.com/7618.html ": None,
    "https://www.vmiba.com/783.html  ": None,
    "https://www.vmiba.com/3444.html ": None,
    "https://www.vmiba.com/4147.html ": None,
    "https://www.vmiba.com/7559.html ": None,
    "https://www.vmiba.com/3441.html ": None,
    "https://www.vmiba.com/3482.html ": None,
    "https://www.vmiba.com/7379.html ": None,
    "https://www.vmiba.com/1049.html ": None,
    "https://www.vmiba.com/4225.html ": None,
    "https://www.vmiba.com/2720.html ": None,
    "https://www.vmiba.com/5464.html ": None,
    "https://www.vmiba.com/3235.html ": None,
    "https://www.vmiba.com/7279.html ": None,
    "https://www.vmiba.com/7274.html ": None,
    "https://www.vmiba.com/7183.html ": None,
    "https://www.vmiba.com/7138.html ": None,
    "https://www.vmiba.com/7121.html ": None,
    "https://www.vmiba.com/7110.html ": None,
    "https://www.vmiba.com/7081.html ": None,
    "https://www.vmiba.com/7061.html ": None,
    "https://www.vmiba.com/7053.html ": None,
    "https://www.vmiba.com/7030.html ": None,
    "https://www.vmiba.com/7013.html ": None,
    "https://www.vmiba.com/6992.html ": None,
    "https://www.vmiba.com/6925.html ": None,
    "https://www.vmiba.com/6919.html ": None,
    "https://www.vmiba.com/6902.html ": None,
    "https://www.vmiba.com/1977.html ": None,
    "https://www.vmiba.com/6829.html ": None,
    "https://www.vmiba.com/988.html  ": None,
    "https://www.vmiba.com/2946.html ": None,
    "https://www.vmiba.com/6683.html ": None,
    "https://www.vmiba.com/6602.html ": None,
    "https://www.vmiba.com/1062.html ": None,
    "https://www.vmiba.com/6516.html ": None,
    "https://www.vmiba.com/6506.html ": None,
    "https://www.vmiba.com/6501.html ": None,
    "https://www.vmiba.com/6475.html ": None,
    "https://www.vmiba.com/6467.html ": None,
    "https://www.vmiba.com/6446.html ": None,
    "https://www.vmiba.com/6441.html ": None,
    "https://www.vmiba.com/1765.html ": None,
    "https://www.vmiba.com/6385.html ": None,
    "https://www.vmiba.com/6220.html ": None,
    "https://www.vmiba.com/6364.html ": None,
    "https://www.vmiba.com/6324.html ": None,
    "https://www.vmiba.com/6284.html ": None,
    "https://www.vmiba.com/2625.html ": None,
    "https://www.vmiba.com/2876.html ": None,
    "https://www.vmiba.com/6176.html ": None,
    "https://www.vmiba.com/6160.html ": None,
    "https://www.vmiba.com/6154.html ": None,
    "https://www.vmiba.com/6151.html ": None,
    "https://www.vmiba.com/4489.html ": None,
    "https://www.vmiba.com/6020.html ": None,
    "https://www.vmiba.com/6009.html ": None,
    "https://www.vmiba.com/4465.html ": None,
    "https://www.vmiba.com/5932.html ": None,
    "https://www.vmiba.com/5906.html ": None,
    "https://www.vmiba.com/5879.html ": None,
    "https://www.vmiba.com/1238.html ": None,
    "https://www.vmiba.com/5841.html ": None,
    "https://www.vmiba.com/5838.html ": None,
    "https://www.vmiba.com/3110.html ": None,
    "https://www.vmiba.com/2940.html ": None,
    "https://www.vmiba.com/4912.html ": None,
    "https://www.vmiba.com/516.html  ": None,
    "https://www.vmiba.com/2357.html ": None,
    "https://www.vmiba.com/1248.html ": None,
    "https://www.vmiba.com/4389.html ": None,
    "https://www.vmiba.com/5497.html ": None,
    "https://www.vmiba.com/3481.html ": None,
    "https://www.vmiba.com/5449.html ": None,
    "https://www.vmiba.com/1563.html ": None,
    "https://www.vmiba.com/2160.html ": None,
    "https://www.vmiba.com/665.html  ": None,
    "https://www.vmiba.com/2144.html ": None,
    "https://www.vmiba.com/3290.html ": None,
    "https://www.vmiba.com/281.html  ": None,
    "https://www.vmiba.com/5118.html ": None,
    "https://www.vmiba.com/2612.html ": None,
    "https://www.vmiba.com/5086.html ": None,
    "https://www.vmiba.com/4781.html ": None,
    "https://www.vmiba.com/4996.html ": None,
    "https://www.vmiba.com/1236.html ": None,
    "https://www.vmiba.com/4941.html ": None,
    "https://www.vmiba.com/4936.html ": None,
    "https://www.vmiba.com/4930.html ": None,
    "https://www.vmiba.com/4916.html ": None,
    "https://www.vmiba.com/4873.html ": None,
    "https://www.vmiba.com/4796.html ": None,
    "https://www.vmiba.com/1987.html ": None,
    "https://www.vmiba.com/1577.html ": None,
    "https://www.vmiba.com/4703.html ": None,
    "https://www.vmiba.com/4746.html ": None,
    "https://www.vmiba.com/4738.html ": None,
    "https://www.vmiba.com/4629.html ": None,
    "https://www.vmiba.com/4622.html ": None,
    "https://www.vmiba.com/4618.html ": None,
    "https://www.vmiba.com/4615.html ": None,
    "https://www.vmiba.com/4496.html ": None,
    "https://www.vmiba.com/4483.html ": None,
    "https://www.vmiba.com/1971.html ": None,
    "https://www.vmiba.com/4418.html ": None,
    "https://www.vmiba.com/4385.html ": None,
    "https://www.vmiba.com/4374.html ": None,
    "https://www.vmiba.com/4326.html ": None,
    "https://www.vmiba.com/4346.html ": None,
    "https://www.vmiba.com/4314.html ": None,
    "https://www.vmiba.com/4287.html ": None,
    "https://www.vmiba.com/4270.html ": None,
    "https://www.vmiba.com/4264.html ": None,
    "https://www.vmiba.com/4252.html ": None,
    "https://www.vmiba.com/4238.html ": None,
    "https://www.vmiba.com/4235.html ": None,
    "https://www.vmiba.com/4216.html ": None,
    "https://www.vmiba.com/2370.html ": None,
    "https://www.vmiba.com/4208.html ": None,
    "https://www.vmiba.com/1575.html ": None,
    "https://www.vmiba.com/4089.html ": None,
    "https://www.vmiba.com/4086.html ": None,
    "https://www.vmiba.com/4072.html ": None,
    "https://www.vmiba.com/2362.html ": None,
    "https://www.vmiba.com/4009.html ": None,
    "https://www.vmiba.com/3905.html ": None,
    "https://www.vmiba.com/3854.html ": None,
    "https://www.vmiba.com/2148.html ": None,
    "https://www.vmiba.com/3824.html ": None,
    "https://www.vmiba.com/3820.html ": None,
    "https://www.vmiba.com/3476.html ": None,
    "https://www.vmiba.com/3395.html ": None,
    "https://www.vmiba.com/3392.html ": None,
    "https://www.vmiba.com/3388.html ": None,
    "https://www.vmiba.com/3294.html ": None,
    "https://www.vmiba.com/3288.html ": None,
    "https://www.vmiba.com/3281.html ": None,
    "https://www.vmiba.com/3229.html ": None,
    "https://www.vmiba.com/3222.html ": None,
    "https://www.vmiba.com/3108.html ": None,
    "https://www.vmiba.com/3170.html ": None,
    "https://www.vmiba.com/3153.html ": None,
    "https://www.vmiba.com/408.html  ": None,
    "https://www.vmiba.com/1496.html ": None,
    "https://www.vmiba.com/2945.html ": None,
    "https://www.vmiba.com/2921.html ": None,
    "https://www.vmiba.com/2949.html ": None,
    "https://www.vmiba.com/2752.html ": None,
    "https://www.vmiba.com/2628.html ": None,
    "https://www.vmiba.com/2643.html ": None,
    "https://www.vmiba.com/341.html  ": None,
    "https://www.vmiba.com/2340.html ": None,
    "https://www.vmiba.com/2435.html ": None,
    "https://www.vmiba.com/2428.html ": None,
    "https://www.vmiba.com/2368.html ": None,
    "https://www.vmiba.com/2274.html ": None,
    "https://www.vmiba.com/2154.html ": None,
    "https://www.vmiba.com/2156.html ": None,
    "https://www.vmiba.com/1983.html ": None,
    "https://www.vmiba.com/1979.html ": None,
    "https://www.vmiba.com/1975.html ": None,
    "https://www.vmiba.com/1989.html ": None,
    "https://www.vmiba.com/1585.html ": None,
    "https://www.vmiba.com/523.html  ": None,
    "https://www.vmiba.com/1973.html ": None,
    "https://www.vmiba.com/1776.html ": None,
    "https://www.vmiba.com/1778.html ": None,
    "https://www.vmiba.com/1591.html ": None,
    "https://www.vmiba.com/1246.html ": None,
    "https://www.vmiba.com/1242.html ": None,
    "https://www.vmiba.com/1054.html ": None,
    "https://www.vmiba.com/984.html  ": None,
    "https://www.vmiba.com/982.html  ": None,
    "https://www.vmiba.com/791.html  ": None,
    "https://www.vmiba.com/785.html  ": None,
    "https://www.vmiba.com/663.html  ": None,
    "https://www.vmiba.com/661.html  ": None,
    "https://www.vmiba.com/659.html  ": None,
    "https://www.vmiba.com/414.html  ": None,
    "https://www.vmiba.com/345.html  ": None,
    "https://www.vmiba.com/343.html  ": None,
    "https://www.vmiba.com/337.html  ": None,
    "https://www.vmiba.com/334.html  ": None,
    "https://www.vmiba.com/285.html  ": None,
    "https://www.vmiba.com/13833.html": None,
    "https://www.vmiba.com/13826.html": None,
    "https://www.vmiba.com/13768.html": None,
    "https://www.vmiba.com/13759.html": None,
    "https://www.vmiba.com/13400.html": None,
    "https://www.vmiba.com/13395.html": None,
    "https://www.vmiba.com/13189.html": None,
    "https://www.vmiba.com/13179.html": None,
    "https://www.vmiba.com/13176.html": None,
    "https://www.vmiba.com/12566.html": None,
    "https://www.vmiba.com/12561.html": None,
    "https://www.vmiba.com/12550.html": None,
    "https://www.vmiba.com/7800.html ": None,
    "https://www.vmiba.com/4179.html ": None,
    "https://www.vmiba.com/12212.html": None,
    "https://www.vmiba.com/12206.html": None,
    "https://www.vmiba.com/11581.html": None,
    "https://www.vmiba.com/11574.html": None,
    "https://www.vmiba.com/10613.html": None,
    "https://www.vmiba.com/4188.html ": None,
    "https://www.vmiba.com/10165.html": None,
    "https://www.vmiba.com/7962.html ": None,
    "https://www.vmiba.com/7934.html ": None,
    "https://www.vmiba.com/9556.html ": None,
    "https://www.vmiba.com/8029.html ": None,
    "https://www.vmiba.com/7917.html ": None,
    "https://www.vmiba.com/9209.html ": None,
    "https://www.vmiba.com/7889.html ": None,
    "https://www.vmiba.com/3400.html ": None,
    "https://www.vmiba.com/7771.html ": None,
    "https://www.vmiba.com/4170.html ": None,
    "https://www.vmiba.com/4195.html ": None,
    "https://www.vmiba.com/5214.html ": None,
    "https://www.vmiba.com/5126.html ": None,
    "https://www.vmiba.com/12653.html": None,
    "https://www.vmiba.com/12008.html": None,
    "https://www.vmiba.com/12001.html": None,
    "https://www.vmiba.com/10402.html": None,
    "https://www.vmiba.com/10398.html": None,
    "https://www.vmiba.com/10054.html": None,
    "https://www.vmiba.com/10022.html": None,
    "https://www.vmiba.com/9905.html ": None,
    "https://www.vmiba.com/9863.html ": None,
    "https://www.vmiba.com/9896.html ": None,
    "https://www.vmiba.com/9884.html ": None,
    "https://www.vmiba.com/9875.html ": None,
    "https://www.vmiba.com/9842.html ": None,
    "https://www.vmiba.com/13871.html": None,
    "https://www.vmiba.com/13861.html": None,
    "https://www.vmiba.com/13854.html": None,
    "https://www.vmiba.com/12846.html": None,
    "https://www.vmiba.com/5225.html ": None,
    "https://www.vmiba.com/11102.html": None,
    "https://www.vmiba.com/10768.html": None,
    "https://www.vmiba.com/10659.html": None,
    "https://www.vmiba.com/10666.html": None,
    "https://www.vmiba.com/3741.html ": None,
    "https://www.vmiba.com/3264.html ": None,
    "https://www.vmiba.com/9737.html ": None,
    "https://www.vmiba.com/7954.html ": None,
    "https://www.vmiba.com/9616.html ": None,
    "https://www.vmiba.com/9090.html ": None,
    "https://www.vmiba.com/8757.html ": None,
    "https://www.vmiba.com/8661.html ": None,
    "https://www.vmiba.com/8657.html ": None,
    "https://www.vmiba.com/8653.html ": None,
    "https://www.vmiba.com/8541.html ": None,
    "https://www.vmiba.com/3119.html ": None,
    "https://www.vmiba.com/4878.html ": None,
    "https://www.vmiba.com/8336.html ": None,
    "https://www.vmiba.com/8322.html ": None,
    "https://www.vmiba.com/8184.html ": None,
    "https://www.vmiba.com/7968.html ": None,
    "https://www.vmiba.com/7940.html ": None,
    "https://www.vmiba.com/7478.html ": None,
    "https://www.vmiba.com/7475.html ": None,
    "https://www.vmiba.com/6564.html ": None,
    "https://www.vmiba.com/6427.html ": None,
    "https://www.vmiba.com/6424.html ": None,
    "https://www.vmiba.com/6403.html ": None,
    "https://www.vmiba.com/6265.html ": None,
    "https://www.vmiba.com/6030.html ": None,
    "https://www.vmiba.com/5230.html ": None,
    "https://www.vmiba.com/4517.html ": None,
    "https://www.vmiba.com/4505.html ": None,
    "https://www.vmiba.com/4501.html ": None,
    "https://www.vmiba.com/4162.html ": None,
    "https://www.vmiba.com/3974.html ": None,
    "https://www.vmiba.com/3971.html ": None,
    "https://www.vmiba.com/3968.html ": None,
    "https://www.vmiba.com/3964.html ": None,
    "https://www.vmiba.com/3738.html ": None,
    "https://www.vmiba.com/3485.html ": None,
    "https://www.vmiba.com/3166.html ": None,
    "https://www.vmiba.com/3160.html ": None,
    "https://www.vmiba.com/2837.html ": None,
    "https://www.vmiba.com/1260.html ": None,
    "https://www.vmiba.com/2795.html ": None,
    "https://www.vmiba.com/2747.html ": None,
    "https://www.vmiba.com/1252.html ": None,
    "https://www.vmiba.com/2605.html ": None,
    "https://www.vmiba.com/2278.html ": None,
    "https://www.vmiba.com/2179.html ": None,
    "https://www.vmiba.com/2174.html ": None,
    "https://www.vmiba.com/2004.html ": None,
    "https://www.vmiba.com/1903.html ": None,
    "https://www.vmiba.com/1899.html ": None,
    "https://www.vmiba.com/1864.html ": None,
    "https://www.vmiba.com/1860.html ": None,
    "https://www.vmiba.com/1846.html ": None,
    "https://www.vmiba.com/1842.html ": None,
    "https://www.vmiba.com/1806.html ": None,
    "https://www.vmiba.com/1745.html ": None,
    "https://www.vmiba.com/1659.html ": None,
    "https://www.vmiba.com/1633.html ": None,
    "https://www.vmiba.com/1629.html ": None,
    "https://www.vmiba.com/1545.html ": None,
    "https://www.vmiba.com/1529.html ": None,
    "https://www.vmiba.com/1502.html ": None,
    "https://www.vmiba.com/1358.html ": None,
    "https://www.vmiba.com/1454.html ": None,
    "https://www.vmiba.com/1410.html ": None,
    "https://www.vmiba.com/1407.html ": None,
    "https://www.vmiba.com/1389.html ": None,
    "https://www.vmiba.com/1365.html ": None,
    "https://www.vmiba.com/1361.html ": None,
    "https://www.vmiba.com/1329.html ": None,
    "https://www.vmiba.com/1326.html ": None,
    "https://www.vmiba.com/1323.html ": None,
    "https://www.vmiba.com/1281.html ": None,
    "https://www.vmiba.com/1274.html ": None,
    "https://www.vmiba.com/1271.html ": None,
    "https://www.vmiba.com/1266.html ": None,
    "https://www.vmiba.com/1263.html ": None
}

# 监控间隔（秒）
interval = 86400  # 一天

# 保存路径
save_path = r"C:\Users\Administrator\Desktop\作品列表"

# 确保保存路径存在
os.makedirs(save_path, exist_ok=True)

def get_structured_content(url):
    """
    获取指定网页中 <div class="article-content clearfix"> 内的结构化内容，直到<div id="html-box-sytzl" class="html-box">
    返回格式：{h3标题: [段落列表]}
    """
    try:
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }
        response = requests.get(url, headers=headers, timeout=10)
        response.raise_for_status()
        
        soup = BeautifulSoup(response.text, 'html.parser')  # 确保soup在函数内部定义
        content_div = soup.find('div', class_='article-content clearfix')
        
        if not content_div:
            logging.warning(f"未找到 <div class='article-content clearfix'> 标签: {url}")
            return {}

        content_dict = {}
        current_h3 = None
        current_paragraphs = []

        for element in content_div.descendants:
            if element.name == 'h3' and ('作品' in element.get_text(strip=True) or '目录' in element.get_text(strip=True) or '列表' in element.get_text(strip=True)):
                if current_h3:
                    content_dict[current_h3] = current_paragraphs
                current_h3 = element.get_text(strip=True)
                current_paragraphs = []
            elif element.name == 'p' and current_h3:
                p_text = element.get_text('\n', strip=True)
                current_paragraphs.append(p_text)
            elif element.name == 'div' and element.has_attr('id') and element['id'] == 'html-box-sytzl':
                break

        if current_h3:
            content_dict[current_h3] = current_paragraphs

        return content_dict

    except requests.RequestException as e:
        logging.error(f"请求异常: {e} - {url}")
        return {}
    except Exception as e:
        logging.error(f"发生未知错误: {e} - {url}")
        return {}

def format_content(content_dict):
    """
    将结构化内容格式化为字符串
    """
    formatted = []
    for h3, paragraphs in content_dict.items():
        formatted.append(f"【{h3}】")
        formatted.extend(paragraphs)
        formatted.append("\n")  # 添加空行分隔不同章节
    return '\n'.join(formatted).strip()

def save_to_file(content, filename):
    full_path = os.path.join(save_path, filename)
    try:
        with open(full_path, 'w', encoding='utf-8', newline='') as f:
            f.write(content)
        logging.info(f"内容已保存到 {full_path}")
    except Exception as e:
        logging.error(f"保存文件时出错: {e} - {full_path}")

def monitor_pages(urls, interval, save_path):
    old_contents = {url: "" for url in urls}
    while True:
        with ThreadPoolExecutor(max_workers=5) as executor:
            future_to_url = {executor.submit(get_structured_content, url): url for url in urls}
            for future in as_completed(future_to_url):
                url = future_to_url[future]
                try:
                    content_dict = future.result()
                    if content_dict:
                        h1_title = BeautifulSoup(requests.get(url, timeout=10).text, 'html.parser').find('h1').get_text(strip=True)
                        filename = f"{h1_title}.txt"
                        new_content = format_content(content_dict)
                        if new_content != old_contents[url]:
                            save_to_file(new_content, filename)
                            old_contents[url] = new_content
                    else:
                        logging.warning(f"未获取到有效内容: {url}")
                except Exception as e:
                    logging.error(f"处理URL时出错: {e} - {url}")
        
        logging.info(f"完成一轮监控，等待 {interval} 秒后进行下一轮监控。")
        time.sleep(interval)

if __name__ == "__main__":
    monitor_pages(urls, interval, save_path)
