import requests
from bs4 import BeautifulSoup
import time
import os
import logging

# 配置日志
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# 监控的网页列表及其对应的保存文件名
urls = {
    "https://www.xsdixiao.com/694.html": "001.白银81.txt",
    "https://www.xsdixiao.com/668.html": "002.桜井宁宁.txt",
    "https://www.xsdixiao.com/696.html": "003.雯妹不讲道理.txt",
    "https://www.xsdixiao.com/520.html": "004.Coser衣衣.txt",
    "https://www.xsdixiao.com/763.html": "005.瓜希酱.txt",
    "https://www.xsdixiao.com/767.html": "006.樱岛嗷一.txt",
    "https://www.xsdixiao.com/534.html": "007.皮皮奶可可爱了啦.txt",
    "https://www.xsdixiao.com/66.html": "008.一笑芳香沁.txt",
    "https://www.xsdixiao.com/877.html": "009.Azami.txt",
    "https://www.xsdixiao.com/900.html": "010.Byoru.txt",
    "https://www.xsdixiao.com/644.html": "011.G44不会受伤.txt",
    "https://www.xsdixiao.com/216.html": "012.izumi泉桃子.txt",
    "https://www.xsdixiao.com/101.html": "013.KaYa萱.txt",
    "https://www.xsdixiao.com/210.html": "014.Kitkat Cosplay 9.txt",
    "https://www.xsdixiao.com/719.html": "015.伊喵君_Nya.txt",
    "https://www.xsdixiao.com/202.html": "016.Messie Huang.txt",
    "https://www.xsdixiao.com/152.html": "017.Momoko葵葵.txt",
    "https://www.xsdixiao.com/745.html": "018. Money冷冷.txt",
    "https://www.xsdixiao.com/761.html": "019.Nyako喵子.txt",
    "https://www.xsdixiao.com/908.html": "020.Potato Godzilla.txt",
    "https://www.xsdixiao.com/845.html": "021.rioko凉凉子.txt",
    "https://www.xsdixiao.com/801.html": "022.小野寺地瓜.txt",
    "https://www.xsdixiao.com/654.html": "023.Shika小鹿鹿.txt",
    "https://www.xsdixiao.com/161.html": "024. Vams子.txt",
    "https://www.xsdixiao.com/1630.html": "025.加冕鱼.txt",
    "https://www.xsdixiao.com/85.html": "026.Yoko宅夏.txt",
    "https://www.xsdixiao.com/140.html": "027. yui金鱼.txt",
    "https://www.xsdixiao.com/252.html": "028.AAAyu阿玉.txt",
    "https://www.xsdixiao.com/731.html": "029.阿包也是兔娘.txt",
    "https://www.xsdixiao.com/178.html": "030.啊日日_Ganlory.txt",
    "https://www.xsdixiao.com/1628.html": "031.肉糊糊.txt",
    "https://www.xsdixiao.com/1538.html": "032.芊芊酱w.txt",
    "https://www.xsdixiao.com/552.html": "033.白烨.txt",
    "https://www.xsdixiao.com/554.html": "034.半半子.txt",
    "https://www.xsdixiao.com/1540.html": "035.可厨.txt",
    "https://www.xsdixiao.com/1527.html": "036.鱼子酱不能睡懒觉.txt",
    "https://www.xsdixiao.com/1525.html": "037.想要搬砖的伶儿.txt",
    "https://www.xsdixiao.com/1529.html": "038.妍子坚不可摧.txt",
    "https://www.xsdixiao.com/168.html": "039.黑川.txt",
    "https://www.xsdixiao.com/874.html": "040.过期米线线喵.txt",
    "https://www.xsdixiao.com/93.html": "041.鬼畜瑶在不在w.txt",
    "https://www.xsdixiao.com/1438.html": "042.流一喵喵喵.txt",
    "https://www.xsdixiao.com/81.html": "043.魔物m.txt",
    "https://www.xsdixiao.com/819.html": "044.疯猫ss.txt",
    "https://www.xsdixiao.com/864.html": "045.二佐Nisa.txt",
    "https://www.xsdixiao.com/879.html": "046.抖娘-利世.txt",
    "https://www.xsdixiao.com/682.html": "047.大大卷卷小卷.txt",
    "https://www.xsdixiao.com/829.html": "048.蠢沫沫.txt",
    "https://www.xsdixiao.com/220.html": "049.沖田凜花Rinka.txt",
    "https://www.xsdixiao.com/1440.html": "050.紫氯氯.txt",
    "https://www.xsdixiao.com/1353.html": "051.腥味猫罐.txt",
    "https://www.xsdixiao.com/749.html": "052.不呆猫.txt",
    "https://www.xsdixiao.com/722.html": "053.抱走莫子aa.txt",
    "https://www.xsdixiao.com/618.html": "054.九曲Jean.txt",
    "https://www.xsdixiao.com/895.html": "055.尤幽.txt",
    "https://www.xsdixiao.com/542.html": "056.鹿野希.txt",
    "https://www.xsdixiao.com/715.html": "057.洛璃 LoLiSAMA.txt",
    "https://www.xsdixiao.com/835.html": "058.秋山AkI.txt",
    "https://www.xsdixiao.com/690.html": "059.麻花麻花酱.txt",
    "https://www.xsdixiao.com/502.html": "060.鳗鱼霏儿.txt",
    "https://www.xsdixiao.com/159.html": "061.猫九酱.txt",
    "https://www.xsdixiao.com/170.html": "062.猫君君.txt",
    "https://www.xsdixiao.com/664.html": "063.快乐的莲某人.txt",
    "https://www.xsdixiao.com/564.html": "064.萌芽儿o0.txt",
    "https://www.xsdixiao.com/365.html": "065.陌九ya.txt",
    "https://www.xsdixiao.com/893.html": "066.蜜汁猫裘.txt",
    "https://www.xsdixiao.com/887.html": "067.面饼仙儿.txt",
    "https://www.xsdixiao.com/678.html": "068.梨瑾瑾.txt",
    "https://www.xsdixiao.com/660.html": "069.tenletters.txt",
    "https://www.xsdixiao.com/624.html": "070.零崎沙耶.txt",
    "https://www.xsdixiao.com/89.html": "071.木花琳琳是勇者.txt",
    "https://www.xsdixiao.com/566.html": "072.木棉棉.txt",
    "https://www.xsdixiao.com/592.html": "073.嗷呜酱.txt",
    "https://www.xsdixiao.com/576.html": "074.奈汐酱nice.txt",
    "https://www.xsdixiao.com/596.html": "075.兮嘻嘻.txt",
    "https://www.xsdixiao.com/733.html": "076.南宫.txt",
    "https://www.xsdixiao.com/560.html": "077.南桃Momoko.txt",
    "https://www.xsdixiao.com/75.html": "078.你的负卿.txt",
    "https://www.xsdixiao.com/79.html": "079.念念_D.txt",
    "https://www.xsdixiao.com/113.html": "080.念雪ww.txt",
    "https://www.xsdixiao.com/837.html": "081.您的蛋蛋.txt",
    "https://www.xsdixiao.com/558.html": "082.七月喵子.txt",
    "https://www.xsdixiao.com/902.html": "083.贰加六.txt",
    "https://www.xsdixiao.com/833.html": "084.绮太郎.txt",
    "https://www.xsdixiao.com/795.html": "085.兔胖胖min.txt",
    "https://www.xsdixiao.com/672.html": "086.小琪-Aki.txt",
    "https://www.xsdixiao.com/91.html": "087.青青子js.txt",
    "https://www.xsdixiao.com/849.html": "088.清水由乃.txt.txt",
    "https://www.xsdixiao.com/729.html": "089.美美丘比酱.txt",
    "https://www.xsdixiao.com/860.html": "090.秋和柯基.txt",
    "https://www.xsdixiao.com/684.html": "091.日奈娇.txt",
    "https://www.xsdixiao.com/913.html": "092.三度_69.txt",
    "https://www.xsdixiao.com/420.html": "093.中華娘娘.txt",
    "https://www.xsdixiao.com/769.html": "094.是依酱吖.txt",
    "https://www.xsdixiao.com/866.html": "095.霜月shimo.txt",
    "https://www.xsdixiao.com/851.html": "096.水淼Aqua.txt",
    "https://www.xsdixiao.com/428.html": "097.蜜嘟喵.txt",
    "https://www.xsdixiao.com/702.html": "098.铁板烧鬼舞w.txt",
    "https://www.xsdixiao.com/432.html": "099.婴紫.txt",
    "https://www.xsdixiao.com/434.html": "100.寶儿Mysterial.txt",
    "https://www.xsdixiao.com/915.html": "101.サクsaku.txt",
    "https://www.xsdixiao.com/727.html": "102.五更百鬼.txt",
    "https://www.xsdixiao.com/402.html": "103.仓鼠姬.txt",
    "https://www.xsdixiao.com/214.html": "104.草莓酱娜.txt",
    "https://www.xsdixiao.com/570.html": "105.夏鸽鸽不想起床.txt",
    "https://www.xsdixiao.com/630.html": "106.徐珺大哥.txt",
    "https://www.xsdixiao.com/314.html": "107.索索-sophia.txt",
    "https://www.xsdixiao.com/805.html": "108.香草喵露露.txt",
    "https://www.xsdixiao.com/584.html": "109.小容仔咕咕咕w.txt",
    "https://www.xsdixiao.com/318.html": "110.肥肥雅.txt",
    "https://www.xsdixiao.com/319.html": "111.姬灵.txt",
    "https://www.xsdixiao.com/708.html": "112.曉美媽.txt",
    "https://www.xsdixiao.com/119.html": "113.星野咪兔.txt",
    "https://www.xsdixiao.com/87.html": "113.星野咪兔.txt",
    "https://www.xsdixiao.com/700.html": "114.星之迟迟.txt",
    "https://www.xsdixiao.com/73.html": "115.摇摇乐yoyo.txt",
    "https://www.xsdixiao.com/436.html": "116.Hyoyeon（金孝渊）.txt",
    "https://www.xsdixiao.com/897.html": "117.桜桃喵.txt",
    "https://www.xsdixiao.com/747.html": "118.雪琪SAMA.txt",
    "https://www.xsdixiao.com/600.html": "119.雪晴Astra.txt",
    "https://www.xsdixiao.com/321.html": "120.骨牙路子野.txt",
    "https://www.xsdixiao.com/735.html": "121.樱落酱w.txt",
    "https://www.xsdixiao.com/323.html": "122.工藤新伍.txt",
    "https://www.xsdixiao.com/628.html": "123.芋圆侑子.txt",
    "https://www.xsdixiao.com/148.html": "124.兔买买bunny.txt",
    "https://www.xsdixiao.com/771.html": "125.在下萝莉控.txt",
    "https://www.xsdixiao.com/632.html": "126.是妃诺呀w.txt",
    "https://www.xsdixiao.com/97.html": "127.周叽是可爱兔兔.txt",
    "https://www.xsdixiao.com/634.html": "128.重生之我是猛男离离.txt",
    "https://www.xsdixiao.com/69.html": "129.一小央泽.txt",
    "https://www.xsdixiao.com/602.html": "130.果咩酱w.txt",
    "https://www.xsdixiao.com/862.html": "131.轩萧学姐.txt",
    "https://www.xsdixiao.com/650.html": "132.小女巫露娜.txt",
    "https://www.xsdixiao.com/787.html": "133.小仓千代w.txt",
    "https://www.xsdixiao.com/377.html": "134.楚楚子w.txt",
    "https://www.xsdixiao.com/99.html": "135.阿薰kaOri.txt",
    "https://www.xsdixiao.com/885.html": "136.怡子yiii.txt",
    "https://www.xsdixiao.com/484.html": "137.Sooflower.txt",
    "https://www.xsdixiao.com/127.html": "138.Kettoe.txt",
    "https://www.xsdixiao.com/797.html": "139.yuuhui玉汇.txt",
    "https://www.xsdixiao.com/186.html": "140.西园寺南歌.txt",
    "https://www.xsdixiao.com/853.html": "141.清青琴玖.txt",
    "https://www.xsdixiao.com/304.html": "142.浅仓yokoo.txt",
    "https://www.xsdixiao.com/739.html": "143.云溪溪.txt",
    "https://www.xsdixiao.com/815.html": "144.一北亦北.txt",
    "https://www.xsdixiao.com/518.html": "145.洛桑w伊梓.txt",
    "https://www.xsdixiao.com/638.html": "146.阿半今天很开心.txt",
    "https://www.xsdixiao.com/759.html": "147.神楽坂真冬.txt",
    "https://www.xsdixiao.com/791.html": "148.三刀刀miido.txt",
    "https://www.xsdixiao.com/482.html": "149.韶陌陌.txt",
    "https://www.xsdixiao.com/656.html": "150.ElyEE子.txt",
    "https://www.xsdixiao.com/400.html": "151.浅野菌子.txt",
    "https://www.xsdixiao.com/680.html": "152.眼酱大魔王w.txt",
    "https://www.xsdixiao.com/129.html": "153.大米米球.txt",
    "https://www.xsdixiao.com/455.html": "154.宫本彩希.txt",
    "https://www.xsdixiao.com/889.html": "155.禅院熏.txt",
    "https://www.xsdixiao.com/192.html": "156.名濑弥七.txt",
    "https://www.xsdixiao.com/460.html": "157.二一不是二一.txt",
    "https://www.xsdixiao.com/462.html": "158.不死原奈.txt",
    "https://www.xsdixiao.com/464.html": "159.慕恩闷贤.txt",
    "https://www.xsdixiao.com/466.html": "160.小无邪和猪小糖.txt",
    "https://www.xsdixiao.com/107.html": "161.黑猫猫ovo.txt",
    "https://www.xsdixiao.com/341.html": "162.嘎潼.txt",
    "https://www.xsdixiao.com/256.html": "163.千煌弑夜.txt",
    "https://www.xsdixiao.com/125.html": "164.蓝小沂KiKi.txt",
    "https://www.xsdixiao.com/294.html": "165.叉子宝宝.txt",
    "https://www.xsdixiao.com/658.html": "166.Sayathefox.txt",
    "https://www.xsdixiao.com/544.html": "167.穆零Mu0.txt",
    "https://www.xsdixiao.com/208.html": "168.あまつ様.txt",
    "https://www.xsdixiao.com/349.html": "169.lovely呆玄.txt",
    "https://www.xsdixiao.com/904.html": "170.Misswarmj小暖.txt",
    "https://www.xsdixiao.com/176.html": "171.弥音音ww.txt",
    "https://www.xsdixiao.com/622.html": "172.爱老师.txt",
    "https://www.xsdixiao.com/337.html": "173.是花花.txt",
    "https://www.xsdixiao.com/150.html": "174.镜酱.txt",
    "https://www.xsdixiao.com/662.html": "175.Yoshinobi .txt",
    "https://www.xsdixiao.com/242.html": "176.花リリ(Plant Lily) .txt",
    "https://www.xsdixiao.com/418.html": "177.御子yumiko.txt",
    "https://www.xsdixiao.com/676.html": "178.沧霁桔梗.txt",
    "https://www.xsdixiao.com/720.html": "179.枸名(逐月su).txt",
    "https://www.xsdixiao.com/608.html": "180.千阳.txt",
    "https://www.xsdixiao.com/646.html": "181.陆卿卿.txt",
    "https://www.xsdixiao.com/258.html": "182.次屁啦.txt",
    "https://www.xsdixiao.com/198.html": "183.妹抖青.txt",
    "https://www.xsdixiao.com/250.html": "184.贞子蜜桃.txt",
    "https://www.xsdixiao.com/236.html": "185.渡边早季Saki.txt",
    "https://www.xsdixiao.com/343.html": "186.尤猫醒醒.txt",
    "https://www.xsdixiao.com/394.html": "187.呀勒呀勒推土君.txt",
    "https://www.xsdixiao.com/174.html": "188.千夜未来.txt",
    "https://www.xsdixiao.com/556.html": "189.千反田鹿子.txt",
    "https://www.xsdixiao.com/109.html": "190.铭铭Kizami.txt",
    "https://www.xsdixiao.com/755.html": "191.花柒Hana .txt",
    "https://www.xsdixiao.com/442.html": "192.一只冉呐.txt",
    "https://www.xsdixiao.com/196.html": "193.猫田圣奈奈.txt",
    "https://www.xsdixiao.com/268.html": "194.Akisoso秋楚楚.txt",
    "https://www.xsdixiao.com/398.html": "195.小酥酱(W黑米粥).txt",
    "https://www.xsdixiao.com/777.html": "196.古川kagura.txt",
    "https://www.xsdixiao.com/422.html": "197.弦音sic.txt",
    "https://www.xsdixiao.com/582.html": "198.弥美Mime.txt",
    "https://www.xsdixiao.com/508.html": "199.白易子教主.txt",
    "https://www.xsdixiao.com/351.html": "200.北之北.txt",
    "https://www.xsdixiao.com/188.html": "201.腐团儿Ikaros.txt",
    "https://www.xsdixiao.com/453.html": "202.Meggii.txt",
    "https://www.xsdixiao.com/572.html": "203.起司块.txt",
    "https://www.xsdixiao.com/458.html": "204.一粒榛子.txt",
    "https://www.xsdixiao.com/383.html": "205.迷失人形QUQ.txt",
    "https://www.xsdixiao.com/234.html": "206.51酱1.txt",
    "https://www.xsdixiao.com/468.html": "207.硫酒Sulfur.txt",
    "https://www.xsdixiao.com/480.html": "208.NinJa阿寨寨.txt",
    "https://www.xsdixiao.com/470.html": "209.千代纸Stella.txt",
    "https://www.xsdixiao.com/206.html": "210.闪月半.txt",
    "https://www.xsdixiao.com/222.html": "211.うたたね翠.txt",
    "https://www.xsdixiao.com/472.html": "212.铅华wr.txt",
    "https://www.xsdixiao.com/474.html": "213.夏美酱.txt",
    "https://www.xsdixiao.com/105.html": "214.chono black.txt",
    "https://www.xsdixiao.com/240.html": "215.佳佳好难啊.txt",
    "https://www.xsdixiao.com/335.html": "216.月城委員会.txt",
    "https://www.xsdixiao.com/692.html": "217.Tina很妖孽呀.txt",
    "https://www.xsdixiao.com/363.html": "218.拿相机的执义.txt",
    "https://www.xsdixiao.com/361.html": "219.茕欢.txt",
    "https://www.xsdixiao.com/248.html": "220.贝儿酱Miki.txt",
    "https://www.xsdixiao.com/476.html": "221.矮乐多Aliga.txt",
    "https://www.xsdixiao.com/478.html": "222.枣糕-下野病弃疗.txt",
    "https://www.xsdixiao.com/606.html": "223.一米八的大梨子.txt",
    "https://www.xsdixiao.com/300.html": "224.渊秧.txt",
    "https://www.xsdixiao.com/165.html": "225.是青水.txt",
    "https://www.xsdixiao.com/546.html": "226.wendydydydy_酱油.txt",
    "https://www.xsdixiao.com/843.html": "227.九九八吖.txt",
    "https://www.xsdixiao.com/1859.html": "228.翎柒菜菜.txt",
    "https://www.xsdixiao.com/510.html": "229.汪知子.txt",
    "https://www.xsdixiao.com/284.html": "230.紫姝Murasaki.txt",
    "https://www.xsdixiao.com/616.html": "231.Yuki亭.txt",
    "https://www.xsdixiao.com/212.html": "232.masaki雅祈.txt",
    "https://www.xsdixiao.com/292.html": "233.Tomiko(とみこ).txt",
    "https://www.xsdixiao.com/131.html": "234.黑白御猫.txt",
    "https://www.xsdixiao.com/813.html": "235.末夜787.txt",
    "https://www.xsdixiao.com/200.html": "236.苏嫣嫣阿姨.txt",
    "https://www.xsdixiao.com/142.html": "237.奇行家狗崽.txt",
    "https://www.xsdixiao.com/486.html": "238.久歌.txt",
    "https://www.xsdixiao.com/709.html": "239.九言.txt",
    "https://www.xsdixiao.com/438.html": "240.Dami (퀸다미).txt",
    "https://www.xsdixiao.com/775.html": "241.木之本果.txt",
    "https://www.xsdixiao.com/753.html": "242.神沢永莉.txt",
    "https://www.xsdixiao.com/446.html": "243.Sunnyvier.txt",
    "https://www.xsdixiao.com/331.html": "244.赛高酱.txt",
    "https://www.xsdixiao.com/204.html": "245.PAKI酱.txt",
    "https://www.xsdixiao.com/274.html": "246.MenruiNyanko.txt",
    "https://www.xsdixiao.com/610.html": "247.北哥完全OK.txt",
    "https://www.xsdixiao.com/516.html": "248.Leah梓未.txt",
    "https://www.xsdixiao.com/278.html": "249.大肉丸Amiee.txt",
    "https://www.xsdixiao.com/182.html": "250.西呱呀呀呀.txt",
    "https://www.xsdixiao.com/870.html": "251.无颜小天使wy.txt",
    "https://www.xsdixiao.com/793.html": "252.兔子Zzz不吃胡萝卜.txt",
    "https://www.xsdixiao.com/648.html": "253.傅四维儿.txt",
    "https://www.xsdixiao.com/614.html": "254.Natsuko夏夏子.txt",
    "https://www.xsdixiao.com/308.html": "255.流年不停w.txt",
    "https://www.xsdixiao.com/799.html": "256.Sayo Momo.txt",
    "https://www.xsdixiao.com/911.html": "257.eliza喵喵.txt",
    "https://www.xsdixiao.com/282.html": "258.甜糖大魔王.txt",
    "https://www.xsdixiao.com/270.html": "259.Fushii_海堂.txt",
    "https://www.xsdixiao.com/451.html": "260.奶兔biubiu.txt",
    "https://www.xsdixiao.com/540.html": "261.是本末末.txt",
    "https://www.xsdixiao.com/711.html": "262.Tomoyo酱.txt",
    "https://www.xsdixiao.com/883.html": "263.桃良阿宅.txt",
    "https://www.xsdixiao.com/218.html": "264.可可老师.txt",
    "https://www.xsdixiao.com/640.html": "265.Kiyo .txt",
    "https://www.xsdixiao.com/604.html": "266.卜呦.txt",
    "https://www.xsdixiao.com/345.html": "267.奶狮不咬人.txt",
    "https://www.xsdixiao.com/449.html": "268.橙喵.txt",
    "https://www.xsdixiao.com/514.html": "269.Quan冉有点饿.txt",
    "https://www.xsdixiao.com/286.html": "270.Hachi 小芭.txt",
    "https://www.xsdixiao.com/233.html": "271.杏仁曲奇.txt",
    "https://www.xsdixiao.com/488.html": "272.苍央鲤庭.txt",
    "https://www.xsdixiao.com/288.html": "273.田璐璐.txt",
    "https://www.xsdixiao.com/190.html": "274.Uki雨季.txt",
    "https://www.xsdixiao.com/180.html": "275.脱尾巴Mizuki.txt",
    "https://www.xsdixiao.com/821.html": "276.星澜是澜澜叫澜妹呀.txt",
    "https://www.xsdixiao.com/262.html": "277.特软儿Sona.txt",
    "https://www.xsdixiao.com/831.html": "278.前羽_rr.txt",
    "https://www.xsdixiao.com/580.html": "279.usejan蓝蓝.txt",
    "https://www.xsdixiao.com/154.html": "280.王胖胖u.txt",
    "https://www.xsdixiao.com/872.html": "281.柒柒要乖哦.txt",
    "https://www.xsdixiao.com/652.html": "282.虎森森.txt",
    "https://www.xsdixiao.com/670.html": "283.菌烨tako.txt",
    "https://www.xsdixiao.com/807.html": "284.花铃.txt",
    "https://www.xsdixiao.com/891.html": "285.阳炎型小菠萝.txt",
    "https://www.xsdixiao.com/290.html": "286.SA_海藻酸钠.txt",
    "https://www.xsdixiao.com/568.html": "287.Meroko_魅瞳.txt",
    "https://www.xsdixiao.com/254.html": "288.zyra秋.txt",
    "https://www.xsdixiao.com/548.html": "289.eloise软软.txt",
    "https://www.xsdixiao.com/855.html": "290.ZinieQ.txt",
    "https://www.xsdixiao.com/713.html": "291.瓦斯塔亚小龙虾.txt",
    "https://www.xsdixiao.com/280.html": "292.七七小姐.txt",
    "https://www.xsdixiao.com/506.html": "293.白神泱Shirag.txt",
    "https://www.xsdixiao.com/194.html": "294.采妮么么(采妮酱).txt",
    "https://www.xsdixiao.com/686.html": "295.晕崽Zz.txt",
    "https://www.xsdixiao.com/312.html": "296.Ruby蘸酱美美.txt",
    "https://www.xsdixiao.com/726.html": "297.胡桃猫Kurumineko.txt",
    "https://www.xsdixiao.com/789.html": "298.女主K.txt",
    "https://www.xsdixiao.com/296.html": "299.啾小妍Deer.txt",
    "https://www.xsdixiao.com/626.html": "300.KANEKO_咔喵.txt",
    "https://www.xsdixiao.com/1812.html": "301.Umeko J.txt",
    "https://www.xsdixiao.com/839.html": "302.露兒大魔王.txt",
    "https://www.xsdixiao.com/440.html": "303.Peach milky.txt",
    "https://www.xsdixiao.com/841.html": "304.巴鲁巴鲁BaRu.txt",
    "https://www.xsdixiao.com/357.html": "305.妖君白研.txt",
    "https://www.xsdixiao.com/666.html": "306.AT鲨.txt",
    "https://www.xsdixiao.com/803.html": "307.你十七鸽.txt",
    "https://www.xsdixiao.com/408.html": "308.无筝Ryou.txt",
    "https://www.xsdixiao.com/528.html": "309.七七娜娜子.txt",
    "https://www.xsdixiao.com/588.html": "310.余多多Dudu.txt",
    "https://www.xsdixiao.com/562.html": "311.河豚抚子.txt",
    "https://www.xsdixiao.com/574.html": "312.巧克力小圆面包.txt",
    "https://www.xsdixiao.com/412.html": "313.白露Bululu.txt",
    "https://www.xsdixiao.com/103.html": "314.从从从从鸾.txt",
    "https://www.xsdixiao.com/612.html": "315.咬一口兔娘.txt",
    "https://www.xsdixiao.com/224.html": "316.斯文文文文 .txt",
    "https://www.xsdixiao.com/642.html": "317.Sally Dorasnow.txt",
    "https://www.xsdixiao.com/310.html": "318.桃墨公子.txt",
    "https://www.xsdixiao.com/704.html": "319.小小奶瓶儿.txt",
    "https://www.xsdixiao.com/246.html": "320.熊丫丫.txt",
    "https://www.xsdixiao.com/244.html": "321.白露很白.txt",
    "https://www.xsdixiao.com/817.html": "322.凛子酱.txt",
    "https://www.xsdixiao.com/1806.html": "323.二阶堂 (宅绘子).txt",
    "https://www.xsdixiao.com/1982.html": "324.鹿八岁baby.txt",
    "https://www.xsdixiao.com/353.html": "325.Miyana咪呀.txt",
    "https://www.xsdixiao.com/333.html": "326.小璐sake.txt",
    "https://www.xsdixiao.com/1810.html": "327.Choi Ji Yun.txt",
    "https://www.xsdixiao.com/1536.html": "328.倦倦喵.txt",
    "https://www.xsdixiao.com/1814.html": "329.年年nnian.txt",
    "https://www.xsdixiao.com/2023.html": "330.Hatori Sama.txt",
    "https://www.xsdixiao.com/1824.html": "331.落落Raku.txt",
    "https://www.xsdixiao.com/272.html": "332.Joyce.txt",
    "https://www.xsdixiao.com/163.html": "333.MissWarmJ.txt",
    "https://www.xsdixiao.com/906.html": "334.黑龙贯通.txt",
    "https://www.xsdixiao.com/1843.html": "335.PoppaChan.txt",
    "https://www.xsdixiao.com/847.html": "336.Hana Bunny.txt",
    "https://www.xsdixiao.com/396.html": "337.切切celia.txt",
    "https://www.xsdixiao.com/444.html": "338.MiMi Chan.txt",
    "https://www.xsdixiao.com/416.html": "339.神探火狸狸.txt",
    "https://www.xsdixiao.com/329.html": "340.Shiroi_白井茶茶.txt",
    "https://www.xsdixiao.com/325.html": "341.蛋黄mayo.txt",
    "https://www.xsdixiao.com/1845.html": "342.Alina Becker.txt",
    "https://www.xsdixiao.com/264.html": "343.Arty亚缇.txt",
    "https://www.xsdixiao.com/115.html": "344.阮邑_Fairy.txt",
    "https://www.xsdixiao.com/688.html": "345.柘烟Zuken.txt",
    "https://www.xsdixiao.com/1932.html": "346.白莉爱吃巧克力.txt",
    "https://www.xsdixiao.com/1869.html": "347.Asagiriai（愛ちゃん）.txt",
    "https://www.xsdixiao.com/1847.html": "348.艾西aiwest.txt",
    "https://www.xsdixiao.com/1966.html": "349.小瑶幺幺.txt",
    "https://www.xsdixiao.com/260.html": "350.十万珍吱伏特.txt",
    "https://www.xsdixiao.com/1980.html": "351.Aery Tiefling.txt",
    "https://www.xsdixiao.com/1997.html": "352.Cat Demon喵崽.txt",
    "https://www.xsdixiao.com/550.html": "353.刺青Poi.txt",
    "https://www.xsdixiao.com/781.html": "354.Luisa_零纱.txt",
    "https://www.xsdixiao.com/1984.html": "355.趴趴捣蛋陌.txt",
    "https://www.xsdixiao.com/765.html": "356.宮本桜.txt",
    "https://www.xsdixiao.com/522.html": "357.狐玖玖.txt",
    "https://www.xsdixiao.com/266.html": "358.六二二同学.txt",
    "https://www.xsdixiao.com/2004.html": "359.屿鱼.txt",
    "https://www.xsdixiao.com/2014.html": "360.いくみ.txt",
    "https://www.xsdixiao.com/2087.html": "361.Seya-狮砸.txt",
    "https://www.xsdixiao.com/2007.html": "362.贝贝琪Becky.txt",
    "https://www.xsdixiao.com/2011.html": "363.泥泥汝.txt",
    "https://www.xsdixiao.com/2009.html": "364.樱梨梨.txt",
    "https://www.xsdixiao.com/302.html": "365.安食Ajiki.txt",
    "https://www.xsdixiao.com/2017.html": "366.小和甜酒.txt",
    "https://www.xsdixiao.com/737.html": "367.w百合欧皇子w.txt",
    "https://www.xsdixiao.com/532.html": "368.紀奈奈 .txt",
    "https://www.xsdixiao.com/2033.html": "369.可可小白兔.txt",
    "https://www.xsdixiao.com/636.html": "370.三色绘恋xFox Hime.txt",
    "https://www.xsdixiao.com/83.html": "371.超级小禾儿.txt",
    "https://www.xsdixiao.com/2082.html": "372.绞肉姬.txt",
    "https://www.xsdixiao.com/785.html": "373.Cien恩恩.txt",
    "https://www.xsdixiao.com/138.html": "374.羊大真人.txt",
    "https://www.xsdixiao.com/578.html": "375.无影喵喵.txt",
    "https://www.xsdixiao.com/586.html": "376.Neko-薇薇.txt",
    "https://www.xsdixiao.com/414.html": "377.吃一口兔子.txt",
    "https://www.xsdixiao.com/2095.html": "378.Puy Puy.txt",
    "https://www.xsdixiao.com/2090.html": "379.楊衣Yangyi.txt",
    "https://www.xsdixiao.com/229.html": "380.佳奈喵.txt",
    "https://www.xsdixiao.com/406.html": "381.神本无尾_Aria.txt",
    "https://www.xsdixiao.com/392.html": "382.薄墨锦狐&三笑.txt",
    "https://www.xsdixiao.com/388.html": "383.许多鱼鱼鱼.txt",
    "https://www.xsdixiao.com/386.html": "384.海沫mmmmm.txt",
    "https://www.xsdixiao.com/384.html": "385.绫Aya.txt",
    "https://www.xsdixiao.com/379.html": "386.羽天Shine.txt",
    "https://www.xsdixiao.com/375.html": "387.时雨-Jiu.txt",
    "https://www.xsdixiao.com/373.html": "388.汐兔子.txt",
    "https://www.xsdixiao.com/371.html": "389.未小寻.txt",
    "https://www.xsdixiao.com/369.html": "390.元素素素素.txt",
    "https://www.xsdixiao.com/367.html": "391.孤毒饮茶.txt",
    "https://www.xsdixiao.com/530.html": "392.机智的哔啵.txt",
    "https://www.xsdixiao.com/538.html": "393.葛生w .txt",
    "https://www.xsdixiao.com/490.html": "394.Pialoof.txt",
    "https://www.xsdixiao.com/347.html": "395.这个泡泡就是逊啦.txt",
    "https://www.xsdixiao.com/492.html": "396.一见倾心.txt",
    "https://www.xsdixiao.com/494.html": "397.二了吧唧.txt",
    "https://www.xsdixiao.com/496.html": "398.君珺un.txt",
    "https://www.xsdixiao.com/526.html": "399.茶籽ccz .txt",
    "https://www.xsdixiao.com/524.html": "400.请叫我若生.txt",
    "https://www.xsdixiao.com/536.html": "401.橙橙yo .txt",
    "https://www.xsdixiao.com/172.html": "402.きょう肉肉.txt",
    "https://www.xsdixiao.com/355.html": "403.九疑.txt",
    "https://www.xsdixiao.com/298.html": "404.妖少you1.txt",
    "https://www.xsdixiao.com/121.html": "405.源纱希喵喵喵.txt",
    "https://www.xsdixiao.com/2113.html": "406.狐洛洛子.txt",
    "https://www.xsdixiao.com/359.html": "407.夏柠柠.txt",
    "https://www.xsdixiao.com/498.html": "408.是澪澪子.txt",
    "https://www.xsdixiao.com/698.html": "409.PingPing.txt",
    "https://www.xsdixiao.com/500.html": "410.翰耐.txt",
    "https://www.xsdixiao.com/598.html": "411.Sameki.txt",
    "https://www.xsdixiao.com/228.html": "412.Miu只.txt",
    "https://www.xsdixiao.com/620.html": "413.恩田直幸.txt",
    "https://www.xsdixiao.com/117.html": "414.小野妹子w.txt",
    "https://www.xsdixiao.com/111.html": "415.墨玉-M.txt",
    "https://www.xsdixiao.com/773.html": "416.eve.txt",
    "https://www.xsdixiao.com/783.html": "417.Uy Uy.txt",
    "https://www.xsdixiao.com/809.html": "418.古阿扎.txt",
    "https://www.xsdixiao.com/858.html": "419.封疆疆v.txt",
    "https://www.xsdixiao.com/881.html": "420.Kuuko W.txt",
    "https://www.xsdixiao.com/757.html": "421.是三不是世w.txt",
    "https://www.xsdixiao.com/424.html": "422.舞小喵.txt",
    "https://www.xsdixiao.com/306.html": "423.椒妮佐仁.txt",
    "https://www.xsdixiao.com/868.html": "424.雨波_HaneAme.txt",
    "https://www.xsdixiao.com/811.html": "425.桜满三时.txt",
    "https://www.xsdixiao.com/674.html": "426.焖焖碳.txt",
    "https://www.xsdixiao.com/430.html": "427.樱群.txt",
    "https://www.xsdixiao.com/751.html": "428.幼愛youmeko.txt",
    "https://www.xsdixiao.com/741.html": "429.Mikehouse.txt",
    "https://www.xsdixiao.com/135.html": "430.仙九Airi.txt",
    "https://www.xsdixiao.com/327.html": "431.清颜真德秀.txt",
    "https://www.xsdixiao.com/339.html": "432.真央Mao.txt",
    "https://www.xsdixiao.com/238.html": "433.仙女月.txt",
    "https://www.xsdixiao.com/123.html": "434.炸酱沐沐.txt",
    "https://www.xsdixiao.com/184.html": "435.洛丽塔大哥.txt",
    "https://www.xsdixiao.com/146.html": "436.是一只熊仔吗.txt",
    "https://www.xsdixiao.com/426.html": "437.嶋葵.txt",
    "https://www.xsdixiao.com/825.html": "438.羽生三未.txt",
    "https://www.xsdixiao.com/410.html": "439.塔塔_Lo1iTa.txt",
    "https://www.xsdixiao.com/512.html": "440.是一只废喵了.txt",
    "https://www.xsdixiao.com/823.html": "441.迷之呆梨.txt",
    "https://www.xsdixiao.com/390.html": "442.戚顾儿MIKI.txt",
    "https://www.xsdixiao.com/743.html": "443.Candy Ball.txt",
    "https://www.xsdixiao.com/71.html": "444.叫我千寻大人.txt",
    "https://www.xsdixiao.com/594.html": "445.如月灰.txt",
    "https://www.xsdixiao.com/2111.html": "446.朝霧愛.txt",
    "https://www.xsdixiao.com/2107.html": "447.糖果果Candy.txt"
}

# 监控间隔（秒）
interval = 86400  # 一天

# 保存路径
save_path = r"C:\Users\Administrator\Desktop\详细目录"

# 确保保存路径存在
os.makedirs(save_path, exist_ok=True)


def get_page_p_content(url):
    """
    获取指定网页中 <div class="entry-content"> 内所有 <p> 标签的文本内容
    :param url: 网页的 URL
    :return: <p> 标签文本内容拼接的字符串
    """
    try:
        # 设置请求头，模拟浏览器访问
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }
        # 发送请求并设置超时时间
        response = requests.get(url, headers=headers, timeout=10)
        response.raise_for_status()  # 检查请求是否成功
        soup = BeautifulSoup(response.text, 'html.parser')
        # 查找 <div class="entry-content"> 标签
        entry_content = soup.find('div', class_='entry-content')
        if entry_content:
            # 提取所有 <p> 标签的文本内容
            p_contents = []
            for p in entry_content.find_all('p'):
                p_text = p.get_text()
                # 保留原有的换行符
                p_contents.append(p_text)
            return '\n'.join(p_contents)
        else:
            logging.warning(f"未找到 <div class='entry-content'> 标签: {url}")
            return ""
    except requests.RequestException as e:
        logging.error(f"请求异常: {e} - {url}")
        return ""
    except Exception as e:
        logging.error(f"发生未知错误: {e} - {url}")
        return ""


def save_to_file(content, filename):
    """
    将内容保存到指定文件
    :param content: 要保存的内容
    :param filename: 保存的文件名
    """
    full_path = os.path.join(save_path, filename)
    try:
        with open(full_path, 'w', encoding='utf-8', newline='') as f:
            f.write(content)
        logging.info(f"内容已保存到 {full_path}")
    except Exception as e:
        logging.error(f"保存文件时出错: {e} - {full_path}")


def monitor_pages(urls, interval, save_path):
    """
    监控指定网页的 <p> 标签内容变化
    :param urls: 网页 URL 与保存文件名的映射字典
    :param interval: 监控间隔时间（秒）
    :param save_path: 保存文件的路径
    """
    # 初始化旧内容字典，初始值设为空字符串便于调试，确保首次运行会保存内容
    old_contents = {url: "" for url in urls}
    while True:
        for url, filename in urls.items():
            # 获取新的内容
            new_content = get_page_p_content(url)
            if new_content != old_contents[url]:
                # 如果内容有变化，则保存新内容
                save_to_file(new_content, filename)
                old_contents[url] = new_content
        logging.info(f"完成一轮监控，等待 {interval} 秒后进行下一轮监控。")
        time.sleep(interval)


if __name__ == "__main__":
    monitor_pages(urls, interval, save_path)